metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - memory
      - network
      - process
      - load
    period: 10s
    hostfs: "/"

setup.kibana:
  host: "http://${KIBANA_HOST}:${KIBANA_PORT}"

output.elasticsearch:
  hosts: ["http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

logging.level: info
logging.to_files: true
logging.files:
  path: "/var/log/metricbeat"
  name: "metricbeat.log"
  keepfiles: 7
  permissions: 0644